is_debug = false
is_official_build = false
is_asan = true
is_ubsan = true
is_ubsan_no_recover = true
symbol_level = 1
is_clang = true
use_sysroot = false
fatal_linker_warnings = false
treat_warnings_as_errors = false
is_cronet_build = true
use_udev = false
use_aura = false
use_ozone = false
use_gio = false
use_platform_icu_alternatives = true
use_glib = false
is_perfetto_embedder = true
disable_file_support = true
enable_websockets = false
use_kerberos = false
disable_zstd_filter = false
enable_mdns = false
enable_reporting = false
include_transport_security_state_preload_list = false
enable_device_bound_sessions = false
enable_bracketed_proxy_uris = true
enable_quic_proxy_support = true
enable_disk_cache_sql_backend = false
use_nss_certs = false
enable_backup_ref_ptr_support = false
enable_dangling_raw_ptr_checks = false
use_clang_modules = false
mac_allow_system_xcode_for_official_builds_for_testing = true
enable_dsyms = false
target_cpu = "arm64"
